### ISSUE TITLE
You can't select deogen

### ISSUE THREAD

**Issue by SomVanTeam** [daedalist/ghostbook#23]
For some reason. when you select evidence for deogen, it doesn't work. Even selecting the Spirit Box (deo's forced evidence) it just won't show deogen.

**Comment by daedalist** [comment]
I can get Deogen to show when selecting DOTS and/or Ghost writing, but it doesn't show when selecting Spirit box.
<img width="498" alt="image" src="https://github.com/daedalist/ghostbook/assets/11693391/3c7d3459-7eb7-43e5-adce-80d598a48951">
